In [8]:
import numpy as np

#task
A = [1,2,3,4,5,6]
type(A)



list

In [10]:
B = np.array(A)

In [11]:
type(B)

numpy.ndarray

In [15]:
c = np.zeros((2,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
D =np.ones((2,3))
print(D)

[[1. 1. 1.]
 [1. 1. 1.]]


AttributeError: module 'numpy' has no attribute 'range'

In [23]:
x = np.array([1,2,3,4], dtype = np.int32)
print(x)

[1 2 3 4]


In [24]:
np.ones(5, dtype = np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [26]:
x = np.random.rand(2,5)
print(x)

[[0.05066055 0.19368598 0.61228725 0.47503146 0.74439024]
 [0.67162184 0.41043055 0.63867226 0.02934333 0.25124363]]


In [ ]:
np.random.randint(1,20, size = (3,3))

array([[ 9,  8, 13],
       [14,  7,  7],
       [ 4, 12, 10]])