In [ ]:
x=[1,2,3,4,5,6]
a=np.array(x)
print(a)

[1 2 3 4 5 6]


In [2]:
import numpy as np


In [ ]:
a.ndim


1

In [ ]:
y=[2,4,6,8,10,12]
b=np.array([x,y])
print(b)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]]


In [ ]:
b.ndim

2

In [ ]:
z=[3,6,9,12,15,18]
c=np.array([x,y,z])
print(c)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]]


In [ ]:
c.ndim

2

In [ ]:
b.shape

(2, 6)

In [ ]:
c.size

18

In [3]:
x=np.arange(1,10)
print(x)


[1 2 3 4 5 6 7 8 9]


In [7]:
y=x.reshape(3,3)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
z=np.transpose(y)
print(z)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [10]:
a = np.arange(1,6)
b = np.arange(6,11)

In [11]:
print(a)

[1 2 3 4 5]


In [12]:
print(b)

[ 6  7  8  9 10]


In [14]:
x=np.vstack((a,b))
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [16]:
y=np.hstack((a,b))
print(y)

[ 1  2  3  4  5  6  7  8  9 10]


In [19]:
a = np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
b = np.arange(1,10).reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
z=np.concatenate((a,b))
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
z=np.concatenate((a,b), axis = 1)
print(z)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


In [25]:
import numpy as np

a = np.arange(9, 22, 3)
b = np.array(2)

print("a:", a)
print("b:", b)

c = a + b
print("a + b:", c)

a: [ 9 12 15 18 21]
b: 2
a + b: [11 14 17 20 23]
