In [1]:
import numpy as np


In [2]:
x=np.random.rand(2,5)
print(x)

[[0.46655434 0.37537475 0.69594328 0.49898817 0.75259311]
 [0.01024674 0.59776358 0.62152739 0.73950543 0.95135774]]


In [6]:
x=np.random.randint(2,8, size = (3,5))
print(x)

[[4 5 4 5 6]
 [5 6 3 5 2]
 [4 7 7 3 3]]


In [11]:
x=np.random.randn(2,5)
print(x)

[[-0.63195047 -0.8713813   0.06295755 -0.26233437 -1.72260535]
 [ 0.40291894 -0.06811667 -0.72892136 -1.36348984  0.76010938]]


In [14]:
x=np.random.choice([1,2,3,4,5,6])
print(x)

5


In [17]:
np.full((2,5),10/2)

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [46]:
np.eye(4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [28]:
np.full(10,2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [29]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(2,12,3)

array([ 2,  5,  8, 11])

In [42]:
np.linspace

array([ 3.        ,  4.16666667,  5.33333333,  6.5       ,  7.66666667,
        8.83333333, 10.        ])

In [47]:
x=np.arange(1,8)
print(x)

[1 2 3 4 5 6 7]


In [48]:
x[1:5]

array([2, 3, 4, 5])

In [52]:
x=np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [68]:
x = np.arange(1,13).reshape(4,3)
print(x)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [83]:
import numpy as np

In [85]:
x=np.arange(1,10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [87]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [88]:
x[1:3,1:3]

array([[5, 6],
       [8, 9]])